#!/usr/bin/env php
<?php

require __DIR__ . '/bootstrap.php';

$commands = \App\Plates\Commandline\CommandContainer::getCommands();

$askedCommand = $argv[1] ?? null;

foreach ($commands as $command) {
    if ($command->getName() === $askedCommand) {
        $command->execute();
        exit(0);
    }
}

echo "Available commands:\n";
foreach ($commands as $command) {
    echo " - " . $command->getName() . "\n";
}
